### ISSUE TITLE
Confusing message: Cannot blink LEDs: Unable to ioctl

### ISSUE THREAD

**Issue by ptesarik** [openSUSE/kdump#28]
Some systems do not have any LEDs that might be used to indicate kdump progress. It would be great to detect such systems and avoid the error message.

**Comment by ptesarik** [comment]
The code here should be reviewed:

https://github.com/openSUSE/kdump/blob/f7f36d6bc8cea49ca1e6298cf51a28d1964de9e1/kdumptool/ledblink.cc#L104

**Comment by jiribohac** [comment]
reworked in v1.9
